### ISSUE TITLE
v0.3.6 flatpak broken in Debian/KDE/Wayland

### ISSUE THREAD

**Issue by dpanter** [flathub/org.rncbc.qpwgraph#18]
Originally posted in https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues/60

Error message when running `flatpak run org.rncbc.qpwgraph`
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
```
QT_QPA_PLATFORM is set to wayland in my environment, but setting something else makes no difference.
Application works again when downgrading to v0.3.5, using this command.

`flatpak update --commit=65e38a39dee64e718411f3de3a3d004eabeea485e5dcec2c763659d82642462d org.rncbc.qpwgraph`

System specs `inxi-b`: https://termbin.com/ldiu

**Comment by travier** [comment]
https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues/60#note_1567373

**Comment by travier** [comment]
Can you try the build from https://github.com/flathub/org.rncbc.qpwgraph/pull/19? Thanks

**Comment by dpanter** [comment]
> Can you try the build from #19? Thanks

That build seems to work properly. Copied from the About box
```
Version: 0.3.6
Using: Qt 6.3.2, libpipewire 0.3.35 (headers: 0.3.35)
```
