### ISSUE TITLE
Saving the patchbay, saves just one connection

### ISSUE THREAD

**Issue by jebofponderworthy** [flathub/org.rncbc.qpwgraph#20]
When I save the patchbay, it saves just one connection.  No errors, no crashing.  This is a rather large patchbay, dozens of links.  How may I help debug?  This is on Manjaro, Pipewire only with its plugins for audio.

**Comment by rncbc** [comment]
unless this is specific to the flatpak please move this to the official upstream tracker: https://gitlab.freedesktop.org/rncbc/qpwgraph

cheers
